(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["compliance-repot-compliance-repot-module~loan-app-loan-app-module~operations-operations-module~organ~4a526e2e"],{

/***/ "./src/app/shared/mocks/mock_common_codes.ts":
/*!***************************************************!*\
  !*** ./src/app/shared/mocks/mock_common_codes.ts ***!
  \***************************************************/
/*! exports provided: COMMON_CODES, PRODUCTS, DISB_VOUCHER, DISBUCEMENTS, LOAN_BREADCRUMBS, RECOVRIES, PRODUCTS2 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "COMMON_CODES", function() { return COMMON_CODES; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PRODUCTS", function() { return PRODUCTS; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "DISB_VOUCHER", function() { return DISB_VOUCHER; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "DISBUCEMENTS", function() { return DISBUCEMENTS; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "LOAN_BREADCRUMBS", function() { return LOAN_BREADCRUMBS; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RECOVRIES", function() { return RECOVRIES; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PRODUCTS2", function() { return PRODUCTS2; });
/* harmony import */ var _models_recovery_model__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../models/recovery.model */ "./src/app/shared/models/recovery.model.ts");
/* harmony import */ var _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../models/recovery.subModel */ "./src/app/shared/models/recovery.subModel.ts");


var COMMON_CODES = [
    'Region Type',
    'Health Insurance Plan',
    'Payment Mode',
    'Income Type',
    'Payment Mode'
];
var PRODUCTS = [
    'KASHF KAROBAR KARZA',
    'EMERGENCY LOAN',
    'HOME IMPROVEMENT LOAN',
    'KASHF AITBAR KARZA',
    'KASHF IBTIDA-E-KAROBAR KARZA',
    'KASHF MURABAHA',
    'KASHF KARZA-E-HASNNA',
    'KASHF SEHATMAND ZINDIGI BEMA'
];
var DISB_VOUCHER = {
    'dsbmtHdrSeq': 1,
    'dsbmtId': null,
    'loanAppSeq': null,
    'dsbmtDt': null,
    'dsbmtStsKey': null,
    'effStartDt': null,
    'effEndDt': null,
    'crtdBy': null,
    'crtdDt': null,
    'lastUpdBy': null,
    'lastUpdDt': null,
    'delFlg': null,
    'crntRecFlg': null,
    'disbursementVoucherDetailDTOs': [
        {
            'dsbmtDtlKey': 6,
            'instrNum': '1234562',
            'amt': 70000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        },
        {
            'dsbmtDtlKey': 5,
            'instrNum': '1234562',
            'amt': 50000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        },
        {
            'dsbmtDtlKey': 4,
            'instrNum': '1234562',
            'amt': 30000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        },
        {
            'dsbmtDtlKey': 3,
            'instrNum': '1234562',
            'amt': 85000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        },
        {
            'dsbmtDtlKey': 2,
            'instrNum': '1234562',
            'amt': 55000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        },
        {
            'dsbmtDtlKey': 1,
            'instrNum': '1234562',
            'amt': 25000,
            'dsbmtHdrSeq': null,
            'pymtTypSeq': null,
            'effStartDt': null,
            'effEndDt': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null,
            'paymtTypesDTO': {
                'typSeq': 1,
                'typStr': null,
                'glAcctNum': null,
                'typStsKey': null,
                'typCtgryKey': null,
                'typId': null,
                'chrgTyp': 'DOCUMENTS CHARGES',
                'effStartDt': null,
                'effEndDt': null,
                'crtdBy': null,
                'crtdDt': null,
                'lastUpdBy': null,
                'lastUpdDt': null,
                'delFlg': null,
                'crntRecFlg': null
            }
        }
    ]
};
var DISBUCEMENTS = [
    {
        'loanAppSeq': 39,
        'loanId': '39',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 40000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 39,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'Ulfat',
            'lastNm': ' Hafeez',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 43,
        'loanId': '43',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 40000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 43,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'khair',
            'lastNm': ' Ulnisa',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 45,
        'loanId': '45',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 40000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 45,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'Syeda',
            'lastNm': 'memona anwar',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 46,
        'loanId': '46',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 50000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 46,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'RAJ',
            'lastNm': ' BIBI',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 49,
        'loanId': '49',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 40000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 49,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'NASREEN',
            'lastNm': ' ',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 50,
        'loanId': '50',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 15000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 50,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'Mehak',
            'lastNm': ' qadeer',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 51,
        'loanId': '51',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 15000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 51,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'NAZIA',
            'lastNm': ' HUSSAIN',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    },
    {
        'loanAppSeq': 52,
        'loanId': '52',
        'loanCyclNum': null,
        'rqstdLoanAmt': null,
        'aprvdLoanAmt': 50000,
        'clntSeq': null,
        'prdSeq': null,
        'rcmndLoanAmt': null,
        'crtdBy': null,
        'crtdDt': null,
        'lastUpdBy': null,
        'lastUpdDt': null,
        'delFlg': null,
        'crntRecFlg': null,
        'effStartDt': null,
        'effEndDt': null,
        'loanAppSts': null,
        'cmnt': null,
        'rejectionReasonCd': null,
        'portSeq': null,
        'loanAppId': null,
        'clientDto': {
            'clntSeq': 52,
            'effStartDt': null,
            'effEndDt': null,
            'clntId': null,
            'cnicNum': null,
            'cnicExpryDt': null,
            'frstNm': 'AYESHA',
            'lastNm': ' SHAFIQ',
            'nickNm': null,
            'mthMadnNm': null,
            'FathrFrstNm': null,
            'fathrLastNm': null,
            'spzFrstNm': null,
            'spzLastNm': null,
            'dob': null,
            'numOfDpnd': null,
            'erngMemb': null,
            'hseHldMemb': null,
            'numOfChldrn': null,
            'numOfErngMemb': null,
            'yrsRes': null,
            'mnthsRes': null,
            'portKey': null,
            'gndrKey': null,
            'mrtlStsKey': null,
            'eduLvlKey': null,
            'occKey': null,
            'natrOfDisKey': null,
            'clntStsKey': null,
            'resTypKey': null,
            'nomDtlAvailableFlg': null,
            'slfPdcFlg': null,
            'crntAddrPermFlg': null,
            'coBwrSanFlg': null,
            'phNum': null,
            'totIncomOfEngMem': null,
            'crtdBy': null,
            'crtdDt': null,
            'lastUpdBy': null,
            'lastUpdDt': null,
            'delFlg': null,
            'crntRecFlg': null
        }
    }
];
var LOAN_BREADCRUMBS = [
    { label: 'MFCIB and Other Loans', href: '/loan-origination/mfcib', isSaved: false, isDisable: false },
    { label: 'Insurance Info', href: '/loan-origination/insurance-info', isSaved: false, isDisable: false },
    { label: 'Nominee Info', href: '/loan-origination/nominee', isSaved: false, isDisable: false },
    { label: 'Co-borrower Info', href: '/loan-origination/co-borrower', isSaved: false, isDisable: false },
    { label: 'Business Appraisal', href: '/loan-origination/business-appraisal', isSaved: false, isDisable: false },
    { label: 'School Appraisal', href: '/loan-origination/school-appraisal', isSaved: false, isDisable: false },
    { label: 'Expected Loan Utilization', href: '/loan-origination/expected-loan-utilication', isSaved: false, isDisable: false },
    { label: 'PSC', href: '/loan-origination/psc', isSaved: false, isDisable: false },
    { label: 'Documents', href: '/loan-origination/documents', isSaved: false, isDisable: false },
    { label: 'Submit Application', href: '/loan-origination/submit', isSaved: false, isDisable: false },
];
var RECOVRIES = [new _models_recovery_model__WEBPACK_IMPORTED_MODULE_0__["Recovery"]({ paySchedDtlSeq: 1, frstNm: 'Amna', lastNm: 'Amna', loanId: 2,
        recoverySub: [
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 1, ppalAmtDue: 20001, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'MobiCash',
                instr: 23432, refCd: 'Overdue11' }),
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 2, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'MobiCash',
                instr: 23432, refCd: 'Overdue12' }),
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 3, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'MobiCash',
                instr: 23432, refCd: 'Overdue12' })
        ]
    }),
    new _models_recovery_model__WEBPACK_IMPORTED_MODULE_0__["Recovery"]({ paySchedDtlSeq: 2, frstNm: 'Mahira', lastNm: 'mahira', loanId: 123213,
        recoverySub: [
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 12323, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'MobiCash',
                instr: 23432, refCd: 'Overdue21' }),
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 12323, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'MobiCash',
                instr: 23432, refCd: 'Overdue22' })
        ]
    }),
    new _models_recovery_model__WEBPACK_IMPORTED_MODULE_0__["Recovery"]({ paySchedDtlSeq: 3, frstNm: 'Arzoo', lastNm: 'arzoo', loanId: 123213,
        recoverySub: [
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 12323, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'Easy Paisa',
                instr: 23432, refCd: 'Overdue31' }),
            new _models_recovery_subModel__WEBPACK_IMPORTED_MODULE_1__["RecoverySub"]({ instNum: 12323, ppalAmtDue: 20000, totChrgDue: 342,
                pymtAmt: 3243, pymtDt: '2/2/2018', rcvryTyp: 'Easy Paisa',
                instr: 23432, refCd: 'Overdue32' })
        ]
    })
];
var PRODUCTS2 = [
    { codeKey: 1, codeValue: 'KASHF KAROBAR KARZA' },
    { codeKey: 2, codeValue: 'EMERGENCY LOAN' }
];


/***/ }),

/***/ "./src/app/shared/models/recovery.model.ts":
/*!*************************************************!*\
  !*** ./src/app/shared/models/recovery.model.ts ***!
  \*************************************************/
/*! exports provided: Recovery */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Recovery", function() { return Recovery; });
var Recovery = /** @class */ (function () {
    function Recovery(obj) {
        this.recoverySub = [];
        //  Object.assign(this, obj);
        //this.recoverySub = [];
    }
    Recovery.prototype.jvId = function (jvId) {
        throw new Error("Method not implemented.");
    };
    return Recovery;
}());



/***/ }),

/***/ "./src/app/shared/models/recovery.subModel.ts":
/*!****************************************************!*\
  !*** ./src/app/shared/models/recovery.subModel.ts ***!
  \****************************************************/
/*! exports provided: RecoverySub */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RecoverySub", function() { return RecoverySub; });
var RecoverySub = /** @class */ (function () {
    function RecoverySub(obj) {
        // Object.assign(this, JSON.parse(JSON.stringify(obj)));
        // this = JSON.parse(JSON.stringify(obj))
        //  this.totalDueAmount = this.ppalAmtDue + this.totChrgDue;
    }
    return RecoverySub;
}());



/***/ })

}]);
//# sourceMappingURL=compliance-repot-compliance-repot-module~loan-app-loan-app-module~operations-operations-module~organ~4a526e2e.js.map